import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy - Gleame",
  description: "Gleame Privacy Policy - How we collect, use, and protect your information.",
};

export default function PrivacyPage() {
  return (
    <div className="py-16 lg:py-24">
      <div className="container">
        <div className="max-w-4xl mx-auto text-gray-600 [&_h1]:text-4xl [&_h1]:font-semibold [&_h1]:text-gray-900 [&_h1]:mb-8 [&_h2]:text-2xl [&_h2]:font-semibold [&_h2]:text-gray-900 [&_h2]:mt-12 [&_h2]:mb-4 [&_h3]:text-xl [&_h3]:font-semibold [&_h3]:text-gray-900 [&_h3]:mt-8 [&_h3]:mb-3 [&_p]:mb-4 [&_p]:leading-relaxed [&_ul]:mb-4 [&_ul]:pl-6 [&_ul]:list-disc [&_ol]:mb-4 [&_ol]:pl-6 [&_ol]:list-decimal [&_li]:mb-2 [&_a]:text-primary [&_a:hover]:underline [&_hr]:my-8 [&_hr]:border-gray-200 [&_code]:bg-gray-100 [&_code]:px-1.5 [&_code]:py-0.5 [&_code]:rounded [&_code]:text-sm [&_strong]:text-gray-900">
          <h1>Privacy Policy</h1>
          
          <p><strong>Effective Date:</strong> April 5, 2026<br />
          <strong>Last Updated:</strong> April 5, 2026</p>

          <p>This Privacy Policy describes how Gleame Inc. (&quot;<strong>Gleame</strong>,&quot; &quot;<strong>we</strong>,&quot; &quot;<strong>us</strong>,&quot; or &quot;<strong>our</strong>&quot;) collects, uses, shares, and protects information in connection with the Gleame Shopify application, the <code>widget-embed.js</code> storefront widget, the Gleame website, and any related services (collectively, the &quot;<strong>Service</strong>&quot;).</p>

          <p>Gleame provides AI-powered virtual try-on technology that allows shoppers on Shopify merchant storefronts to upload a photograph of themselves and preview how beauty and skincare products may appear on their face.</p>

          <p>This Policy applies to two distinct categories of individuals:</p>

          <ol>
            <li><strong>Merchants</strong> — Shopify store owners and their authorized staff who install and use the Gleame app.</li>
            <li><strong>End Users / Shoppers</strong> — individuals who interact with the Gleame virtual try-on widget on a merchant&apos;s storefront.</li>
          </ol>

          <p>If you are a shopper and have questions about how a specific store uses your data, please also review that merchant&apos;s own privacy policy. Each merchant is an independent data controller for the personal data of its own customers; Gleame acts as a data processor on the merchant&apos;s behalf when operating the widget.</p>

          <hr />

          <h2>1. Information We Collect</h2>

          <h3>1.1 Information from Merchants</h3>

          <p>When a merchant installs or uses the Gleame app, we collect:</p>

          <ul>
            <li><strong>Shopify account data</strong> provided via Shopify OAuth: shop domain, shop ID, store name, contact email, country, plan, currency, timezone, and the access scopes granted to the app.</li>
            <li><strong>Product and catalog data</strong>: product titles, descriptions, variants, images, metafields, tags, and related catalog information retrieved through the Shopify Admin API in order to configure virtual try-on.</li>
            <li><strong>Order and analytics data</strong>: order events, cart tokens, checkout and conversion data (via <code>orders/create</code> and related webhooks) used to attribute purchases to try-on sessions and to compute pricing tiers based on Shopify monthly sessions.</li>
            <li><strong>Merchant configuration</strong>: product-to-parameter mappings, AI prompt configurations, widget style choices, reference images uploaded by the merchant, and similar settings.</li>
            <li><strong>Billing data</strong>: subscription status, plan tier, and transaction metadata managed through Hey Mantle. We do not store full payment card numbers; billing is handled by Shopify and Mantle.</li>
            <li><strong>Support and communications</strong>: information you provide when you contact us (name, email, message contents).</li>
          </ul>

          <h3>1.2 Information from End Users (Shoppers)</h3>

          <p>When a shopper interacts with the Gleame widget on a merchant&apos;s storefront, we may process:</p>

          <ul>
            <li><strong>Facial images / selfies</strong> that the shopper voluntarily uploads or captures for the purpose of generating a virtual try-on preview. These images depict the shopper&apos;s face and, under certain laws (including Illinois BIPA and similar statutes), may be considered <strong>biometric information</strong> or <strong>sensitive personal data</strong>. See Section 5.</li>
            <li><strong>Transformed output images</strong> generated by the AI models.</li>
            <li><strong>Limited usage data</strong>: event type (widget viewed, transformation requested, product added to cart), the product and widget style involved, the shop domain, and a timestamp. We transiently use the shopper&apos;s IP address to enforce rate limits on the transform endpoint, but we do <strong>not</strong> store IP addresses, user-agent strings, device fingerprints, or approximate location derived from IP.</li>
            <li><strong>Cart and conversion linkage</strong>: the Shopify cart token associated with a try-on session so that a subsequent purchase can be attributed to the session via the <code>orders/create</code> webhook.</li>
            <li><strong>No cookies or browser storage</strong>: the Gleame widget does not set cookies or write to <code>localStorage</code> / <code>sessionStorage</code>. The shopper&apos;s cart token is read from the surrounding storefront page at the moment of the transform request. We do not operate any cross-site advertising or behavioral-tracking infrastructure.</li>
          </ul>

          <h3>1.3 Information We Do Not Knowingly Collect</h3>

          <ul>
            <li>We do not knowingly collect personal data from children under the age of 13 (or the applicable minimum age in your jurisdiction). The Service is not directed at children. See Section 10.</li>
            <li>We do not request government identifiers, financial account numbers, health records, or precise geolocation from shoppers.</li>
          </ul>

          <hr />

          <h2>2. How We Use Information</h2>

          <p>We use the information described above for the following purposes:</p>

          <ol>
            <li><strong>Providing the Service</strong>: authenticating merchants through Shopify, rendering the try-on widget, processing images through AI models, generating output previews, and returning results to the shopper&apos;s browser.</li>
            <li><strong>AI image transformation</strong>: temporarily sending uploaded images and prompt instructions to our AI sub-processors (see Section 4) to produce virtual try-on results.</li>
            <li><strong>Analytics and attribution</strong>: measuring widget usage, conversion rates, and try-on performance, and reporting these metrics to the merchant.</li>
            <li><strong>Billing and tier assignment</strong>: determining the merchant&apos;s pricing tier based on Shopify monthly sessions and managing subscription status via Hey Mantle.</li>
            <li><strong>Security, abuse prevention, and rate limiting</strong>: detecting fraudulent, abusive, or unlawful activity, including protection of the <code>/api/storefront/transform-image</code> endpoint.</li>
            <li><strong>Product improvement</strong>: diagnosing errors, debugging, and improving quality of the Service. Gleame does <strong>not</strong> use shopper facial images to train or fine-tune any AI models operated by Gleame, and does not retain source images beyond the transient processing described in Section 5.2. Shopper images are transmitted to Gemini or OpenAI only for the duration of the transform request; how those providers handle inputs on their side is governed by their own data-use policies applicable to the API tier used.</li>
            <li><strong>Customer support and communications</strong>: responding to inquiries, sending service-related messages, and notifying merchants of important changes.</li>
            <li><strong>Legal compliance</strong>: complying with applicable law, lawful requests from authorities, and enforcement of our Terms of Service.</li>
          </ol>

          <h3>Legal Bases (GDPR / UK GDPR)</h3>

          <p>Where the GDPR or UK GDPR applies, we rely on the following legal bases:</p>

          <ul>
            <li><strong>Contract</strong> — to deliver the Service requested by a merchant or shopper.</li>
            <li><strong>Legitimate interests</strong> — to operate, secure, and improve the Service, provided those interests are not overridden by your rights.</li>
            <li><strong>Consent</strong> — for the processing of facial images/biometric data by shoppers (obtained at the point of upload) and for any optional features that require consent.</li>
            <li><strong>Legal obligation</strong> — to comply with applicable laws.</li>
          </ul>

          <p>A shopper may withdraw consent at any time by declining to upload an image or by contacting us or the merchant as described in Section 8. Withdrawal does not affect the lawfulness of processing before withdrawal.</p>

          <hr />

          <h2>3. How We Share Information</h2>

          <p>We share information only as described below. <strong>We do not sell personal information</strong>, and we do not share personal information for cross-context behavioral advertising as those terms are defined under the California Consumer Privacy Act (CCPA/CPRA).</p>

          <ul>
            <li><strong>With merchants</strong>: shopper-level analytics (in aggregated and, where relevant to conversion attribution, individual session form) are made available to the merchant whose storefront the shopper used.</li>
            <li><strong>With Shopify</strong>: as required to operate as a Shopify app, including webhooks and Admin API calls.</li>
            <li><strong>With sub-processors</strong> (see Section 4).</li>
            <li><strong>With professional advisors</strong>: lawyers, auditors, and accountants under obligations of confidentiality.</li>
            <li><strong>In a corporate transaction</strong>: in connection with a merger, acquisition, financing, reorganization, bankruptcy, or sale of assets, subject to standard confidentiality protections.</li>
            <li><strong>To comply with law or protect rights</strong>: to respond to lawful requests, enforce our Terms, or protect the rights, property, or safety of Gleame, our users, or others.</li>
          </ul>

          <hr />

          <h2>4. Sub-Processors</h2>

          <p>We use the following categories of sub-processors to deliver the Service. Each is bound by written terms requiring appropriate security and confidentiality:</p>

          <div className="overflow-x-auto">
            <table className="min-w-full text-sm">
              <thead>
                <tr>
                  <th className="text-left py-2 px-4 border-b">Sub-processor</th>
                  <th className="text-left py-2 px-4 border-b">Purpose</th>
                  <th className="text-left py-2 px-4 border-b">Data processed</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td className="py-2 px-4 border-b"><strong>Shopify Inc.</strong></td>
                  <td className="py-2 px-4 border-b">App platform, OAuth, Admin API, webhooks</td>
                  <td className="py-2 px-4 border-b">Merchant and store data</td>
                </tr>
                <tr>
                  <td className="py-2 px-4 border-b"><strong>Google LLC (Gemini API)</strong></td>
                  <td className="py-2 px-4 border-b">Primary AI image transformation</td>
                  <td className="py-2 px-4 border-b">Shopper facial images and prompt text, transiently during the API call</td>
                </tr>
                <tr>
                  <td className="py-2 px-4 border-b"><strong>OpenAI, L.L.C.</strong></td>
                  <td className="py-2 px-4 border-b">Secondary / fallback AI image transformation</td>
                  <td className="py-2 px-4 border-b">Shopper facial images and prompt text, transiently during the API call</td>
                </tr>
                <tr>
                  <td className="py-2 px-4 border-b"><strong>Supabase, Inc.</strong></td>
                  <td className="py-2 px-4 border-b">Primary application database (PostgreSQL) and storage</td>
                  <td className="py-2 px-4 border-b">Merchant accounts, product/variant configuration, analytics events, reference images</td>
                </tr>
                <tr>
                  <td className="py-2 px-4 border-b"><strong>Render, Inc.</strong></td>
                  <td className="py-2 px-4 border-b">Application hosting and compute</td>
                  <td className="py-2 px-4 border-b">All data in transit through the Service</td>
                </tr>
                <tr>
                  <td className="py-2 px-4 border-b"><strong>Hey Mantle</strong></td>
                  <td className="py-2 px-4 border-b">Subscription billing and usage-based metering</td>
                  <td className="py-2 px-4 border-b">Merchant billing metadata (no card data)</td>
                </tr>
                <tr>
                  <td className="py-2 px-4 border-b"><strong>Resend</strong></td>
                  <td className="py-2 px-4 border-b">Transactional email delivery</td>
                  <td className="py-2 px-4 border-b">Merchant contact email addresses</td>
                </tr>
                <tr>
                  <td className="py-2 px-4 border-b"><strong>Intercom, Inc.</strong></td>
                  <td className="py-2 px-4 border-b">In-app merchant support chat</td>
                  <td className="py-2 px-4 border-b">Merchant identifiers and support conversation contents</td>
                </tr>
              </tbody>
            </table>
          </div>

          <p>We will update this list as sub-processors change. Shopper facial images are sent to Gemini or OpenAI only for the transient purpose of generating a requested try-on preview.</p>

          <hr />

          <h2>5. Biometric / Facial Data — Special Notices</h2>

          <p>Gleame&apos;s core functionality requires processing images of human faces. Depending on jurisdiction, these images and any features derived from them may be considered <strong>biometric identifiers</strong>, <strong>biometric information</strong>, or <strong>sensitive personal data</strong>.</p>

          <h3>5.1 Purpose and Consent</h3>

          <p>Facial images are processed <strong>solely for the purpose of generating a virtual try-on preview</strong> requested by the shopper. Before uploading, shoppers are shown a notice and must affirmatively proceed, which constitutes their consent to processing for this purpose.</p>

          <h3>5.2 Retention and Deletion</h3>

          <ul>
            <li><strong>Uploaded source images (shopper selfies) are not stored on Gleame servers.</strong> When a shopper uploads a photo, the image is held in server memory only for the duration of the transform request: it is resized, transmitted over TLS to the AI sub-processor, and discarded when the HTTP response is returned. Gleame does not write the source image to any database, disk, object store, log, or backup.</li>
            <li><strong>Transformed output images are not stored on Gleame servers either.</strong> The AI-generated preview is returned directly to the shopper&apos;s browser in the API response and rendered client-side. Gleame does not persist generated previews.</li>
            <li><strong>No biometric templates or faceprints.</strong> We do not construct, store, or query persistent biometric templates, faceprints, embeddings, or face-recognition identifiers from shopper images. The Service does not perform identification, verification, matching, or re-identification of individuals.</li>
            <li><strong>Merchant-uploaded reference images</strong> (product photographs or style references uploaded by the merchant from the admin app) are stored in Supabase for the duration of the merchant&apos;s installation and are deleted when the merchant removes them or uninstalls the app.</li>
          </ul>

          <h3>5.3 No Sale, No Profiling, No Secondary Use</h3>

          <p>We do not sell, lease, trade, or otherwise profit from biometric information. We do not use shopper facial images for advertising, for building identification databases, or for training AI models.</p>

          <h3>5.4 Illinois BIPA and Similar State Laws</h3>

          <p>For shoppers in Illinois, Texas, Washington, and other jurisdictions with biometric privacy statutes, you are hereby notified that:</p>

          <ol>
            <li>The Service collects facial images that may constitute biometric information.</li>
            <li>The specific purpose of collection is virtual try-on preview generation.</li>
            <li>The length of time for which the information will be stored and used is described in Section 5.2 and Section 7.</li>
            <li>Your affirmative action to upload an image constitutes your written consent to collection, storage, and use for the stated purpose.</li>
            <li>We will not disclose biometric information except as described in Sections 3 and 4, or as required by law.</li>
          </ol>

          <p>If you do not consent, do not upload an image.</p>

          <hr />

          <h2>6. International Data Transfers</h2>

          <p>Gleame is operated from the United States and uses sub-processors located in the United States and other jurisdictions. If you access the Service from outside the United States, your information may be transferred to, stored, and processed in countries whose data protection laws differ from those of your own jurisdiction.</p>

          <p>Where required, we rely on appropriate safeguards such as the <strong>Standard Contractual Clauses</strong> approved by the European Commission, the <strong>UK International Data Transfer Addendum</strong>, and equivalent mechanisms. A copy of the relevant safeguards is available on request.</p>

          <hr />

          <h2>7. Data Retention</h2>

          <p>We retain information only as long as necessary for the purposes described in this Policy:</p>

          <ul>
            <li><strong>Shopper source images (selfies)</strong>: <strong>not retained.</strong> Processed in memory only during the transform request, as described in Section 5.2.</li>
            <li><strong>AI-generated preview images</strong>: <strong>not retained server-side.</strong> Returned directly to the shopper&apos;s browser.</li>
            <li><strong>Analytics events and conversion records</strong> (event type, product, shop domain, cart token, timestamp): retained for the duration of the merchant&apos;s installation to power the analytics dashboard and to support accurate conversion attribution over time. These records are deleted when the merchant uninstalls the app or upon a valid <code>shop/redact</code> request.</li>
            <li><strong>Merchant account and configuration data</strong> (shop record, products, variants, reference images, AI prompt configurations): retained for the duration of the merchant&apos;s installation and deleted when the merchant uninstalls the app or upon a valid <code>shop/redact</code> request.</li>
            <li><strong>Billing records</strong> (subscription status, usage metering metadata): retained by Gleame and by Hey Mantle as required by applicable financial recordkeeping laws.</li>
            <li><strong>Support communications</strong> (Intercom, email): retained for as long as reasonably necessary to provide ongoing support and to maintain a history of reported issues.</li>
          </ul>

          <hr />

          <h2>8. Your Rights</h2>

          <p>Depending on your jurisdiction, you may have the following rights:</p>

          <ul>
            <li><strong>Access</strong> — request a copy of personal data we hold about you.</li>
            <li><strong>Rectification</strong> — correct inaccurate or incomplete data.</li>
            <li><strong>Erasure (&quot;right to be forgotten&quot;)</strong> — request deletion of your data.</li>
            <li><strong>Restriction</strong> — restrict processing in certain circumstances.</li>
            <li><strong>Portability</strong> — receive your data in a portable, machine-readable format.</li>
            <li><strong>Objection</strong> — object to processing based on legitimate interests.</li>
            <li><strong>Withdrawal of consent</strong> — withdraw consent at any time without affecting prior lawful processing.</li>
            <li><strong>Non-discrimination</strong> — exercise your rights without retaliation (CCPA/CPRA).</li>
            <li><strong>Opt out of sale or sharing</strong> — not applicable, because we do not sell or share personal data for cross-context behavioral advertising.</li>
            <li><strong>Lodge a complaint</strong> — with your local supervisory authority.</li>
          </ul>

          <h3>How to Exercise Your Rights</h3>

          <ul>
            <li><strong>Shoppers</strong>: contact the merchant whose storefront you used; they are the data controller. You may also contact us at <strong>aaron@gleame.ai</strong> and we will route your request appropriately.</li>
            <li><strong>Merchants</strong>: email <strong>aaron@gleame.ai</strong> from the address associated with your Shopify store.</li>
          </ul>

          <p>We will respond within the timeframes required by applicable law (generally 30 days under the GDPR, 45 days under the CCPA, extendable where permitted). We may need to verify your identity before fulfilling a request.</p>

          <hr />

          <h2>9. Security</h2>

          <p>We implement commercially reasonable technical and organizational measures to protect personal data, including:</p>

          <ul>
            <li>TLS 1.2+ encryption in transit for all API traffic.</li>
            <li>Encryption at rest for databases and object storage, via our hosting providers.</li>
            <li>Least-privilege access controls, audit logging, and secret management.</li>
            <li>Shop-domain verification on the storefront API to prevent cross-shop data access.</li>
            <li>Rate limiting on public endpoints to mitigate abuse.</li>
            <li>Regular dependency patching and vulnerability review.</li>
          </ul>

          <p>No method of transmission or storage is 100% secure. We cannot guarantee absolute security, but we will notify affected individuals and authorities of any personal data breach as required by applicable law.</p>

          <hr />

          <h2>10. Children</h2>

          <p>The Service is not directed to children under the age of 13, and we do not knowingly collect personal information from children under 13. For shoppers in the EEA / UK, the minimum age is 16 unless a lower age is provided by applicable local law. If you believe a child has provided us with personal information, please contact us and we will delete it.</p>

          <p>Merchants are responsible for ensuring that their own use of the Service complies with laws applicable to minors in the jurisdictions in which they operate.</p>

          <hr />

          <h2>11. Cookies and Tracking Technologies</h2>

          <p><strong>The Gleame storefront widget does not set cookies or write to <code>localStorage</code> or <code>sessionStorage</code>.</strong> It does not use third-party advertising cookies, pixels, or cross-site trackers. Conversion attribution is performed by reading the Shopify cart token already present on the storefront page at the moment of the try-on request and matching it server-side against the subsequent <code>orders/create</code> webhook — no client-side tracking identifier is stored on the shopper&apos;s device.</p>

          <p>The Gleame merchant admin app (accessible only to authenticated merchants inside the Shopify admin) uses cookies and session storage to the extent required by Shopify App Bridge, Shopify OAuth, and our support-chat provider (Intercom). These are not present on shopper-facing storefronts.</p>

          <p>Merchants remain responsible for any additional cookies set by their own storefront theme and for displaying any cookie banners required by law (e.g., the EU ePrivacy Directive).</p>

          <hr />

          <h2>12. California Privacy Rights (CCPA / CPRA)</h2>

          <p>California residents have the rights described in Section 8. In the preceding 12 months we have collected the categories of personal information described in Section 1 for the business purposes described in Section 2. We have <strong>not sold</strong> and have <strong>not shared</strong> personal information for cross-context behavioral advertising. We do not knowingly collect or sell the personal information of minors under 16.</p>

          <p>To exercise your rights, contact <strong>aaron@gleame.ai</strong>. An authorized agent may submit a request on your behalf with proof of authorization.</p>

          <hr />

          <h2>13. Changes to This Policy</h2>

          <p>We may update this Privacy Policy from time to time. When we do, we will update the &quot;Last Updated&quot; date at the top and, for material changes, provide additional notice (for example, via email to merchants or a prominent notice in the app). Your continued use of the Service after the updated Policy takes effect constitutes acceptance of the changes.</p>

          <hr />

          <h2>14. Contact Us</h2>

          <p>If you have questions, concerns, or requests regarding this Privacy Policy or our data practices, contact:</p>

          <p>
            <strong>Gleame Inc.</strong><br />
            Attn: Privacy<br />
            2722 S. Figueroa St.<br />
            Los Angeles, CA 90007<br />
            USA<br />
            Email: <strong>aaron@gleame.ai</strong>
          </p>
        </div>
      </div>
    </div>
  );
}
